### ISSUE TITLE
Crash on old intel cpus

### ISSUE THREAD

**Issue by jack5d** [otavioarj/KiInjector#1]
Hi, release 4 is crashing on every cpu older than I7 Gen4 cpus. Reading your project config, -march=native is present, so you're forcing some real new instruction fetch.

Is that really necessary or just an optimization approach?

**Comment by otavioarj** [comment]
It isn't necessary, my bad :). As I have only Skylake CPUs, combined with -OFast optimization from GCC 6.3, it may had added some pretty cool instructions which causes crash while running in older CPUs.

Next release I will add executables with Core2 support, it's safe for AMD users also :).
