### ISSUE TITLE
Replace EnumProcesses with NtQuerySystemInformation

### ISSUE THREAD

**Issue by bugproof** [otavioarj/KiInjector#2]
You should be using NtQuerySystemInformation to enumerate the processes. The injector doesn't find them all even in administrator mode.

**Comment by otavioarj** [comment]
Yeah,  NtQuerySystemInformation will return all process (x86 or x86_64), you're right :).
But, it will find not "injectable" process also; using x86 (PE32) while on Winx64 it will return x64 process, and on x64(PE32+) it will return exclusive x86 (Wow64) process.  

I can make the x64 version checks process information and DLL PE header to ensure both are exclusively x86? Yes, it's possible, it's even more elegant! Having only one executable capable to inject both x86 and x86_64 while on Win64... 

But it isn't practical :) What you're probably doing is compiling it to x86_64 and trying to enumerates x86 process, or for x86 trying to enumerating x64 process. It doesn't work this way, you have to build x86 for x86 process/dll and x86_64 for x64 process/dll.

**Comment by himajara** [comment]
NtQuerySystemInformation does return all available process, independent of arch and permission, isn't? So are yoy saying that your way only return process capable of been injected, right? 

Even as admin I can't list System process/services, as the permission checks returns false. Fix me if wrong.

**Comment by otavioarj** [comment]
NtQuerySystemInformation is the right way, as it returns every process (even services). But not all of these process can be inject: permissions or arch (the injector have x86 and x86_64 arch!) restriction.

So, yes @himajara your right, you can't inject into System process (LPP flag :P) as even the Admin doesn't have permissions to manipulate some process.

If @fmj02 doesn't have any questions, I will close the issue :)
