### ISSUE TITLE
I can't build x64 version

### ISSUE THREAD

**Issue by himajara** [otavioarj/KiInjector#3]
Using QT5.2 and GCC 5.4 I can't build the intel x86 64 bits version. The compiler results in a large group of errors. Can you provide compiler toolchain for build this?

**Comment by otavioarj** [comment]
Try using https://mingw-w64.org . The version of the gcc+winapi is better done and *x86_64* is available :).
Create a new compiler entry into Qt Assist, so you can use it :).
